name: Build Docker Containers

on:
  workflow_dispatch:
    inputs: 

    image_name:
      required: true
      default: "be_the_whale_image.tar"

    additional_args:
      required: false
      default: ""



jobs:
  Build:

    if: github.event_name == 'workflow_dispatch'

    runs-on: ubuntu-latest

    name: Manual Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |

          chmod +x build_image.sh
          ./build_image.sh ${{ inputs.image_name }} ${{ inputs.additional_args }}

      - name: Save as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build_image 
          path: "images/${{inputs.image_name}}"

