name: Build Docker Containers

on:
  workflow_dispatch:
    inputs: 

    name:
      description: 'name for the final image'
      required: true
      default: 'dev'
      type: string

jobs:
  Build:

    if: github.event_name == 'workflow_dispatch'

    runs-on: ubuntu-latest

    name: Manual Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |

          chmod +x build_image.sh
          ./build_image.sh -n ${{ inputs.name }}

      - name: Save as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build_image 
          path: "images/${{ inputs.name }}"

